language: python

branches:
  only:
    - master
    - travis

python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Setup anaconda
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblapack-dev libopenblas-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install -y gfortran

# Install packages
install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install scipy
  - pip install xlsxwriter
  - pip install matplotlib
  - pip install coveralls
  - python setup.py install

script:
  - source activate $TRAVIS_PYTHON_VERSION
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=wdmtoolbox --cover-branches --cover-erase

after_success:
  - coveralls
