#!/bin/bash

program=wdmtoolbox

pkg=" \
     setuptools \
     atlas \
     numpy \
     scipy \
     matplotlib \
     nose \
     dateutil \
     pandas \
     pip \
     coverage \
     flake8 \
     "

# pandas no longer supports 2.6
envs=(2.7 3.3 3.4 3.5)

for env in ${envs[@]}; do
    echo "${env}"

    pew in python${env} << EOT
    pip install --upgrade ${pkgs}
    pip install --no-deps --upgrade ../mando/
    pip uninstall -y ${program}
    rm -rf build
    pip install --upgrade --no-deps ../${program}/

    nosetests \
        --with-doctest \
        --with-coverage \
        --cover-tests \
        --cover-package=${program} \
        --cover-branches \
        --cover-erase
EOT
done

pew in python3.4 << EOTT
coverage erase
coverage run `which nosetests` --with-doctest
coverage report --include="wdmtoolbox/*" --omit="tests/*" --omit=".tox/*"
coverage html --include="wdmtoolbox/*" --omit="tests/*" --omit=".tox/*"
flake8 wdmtoolbox/__init__.py wdmtoolbox/wdmutil.py --exit-zero

cd docsrc
make clean
make html
EOTT



