#!/bin/bash

program=wdmtoolbox

pkg=" \
     setuptools \
     atlas \
     numpy \
     scipy \
     matplotlib \
     nose \
     dateutil \
     pandas \
     pip \
     coverage \
     flake8 \
     mando \
     "

# pandas no longer supports 2.6
envs=(~/python_ves/python-2.7.13\
      ~/python_ves/python-3.4.5 \
      ~/python_ves/python-3.5.2 \
      ~/python_ves/python-3.6.0)

for env in ${envs[@]}; do
    echo "${env}"

    source "${env}"/bin/activate
    pip install --upgrade pip
    pip install --upgrade ${pkgs}
    pip uninstall -y ${program}
    rm -rf build
    pip install --upgrade --no-deps ../${program}/

    nosetests \
        --with-doctest \
        --with-coverage \
        --cover-tests \
        --cover-package=${program} \
        --cover-branches \
        --cover-erase
    deactivate
done

# source ~/python_ves/python-3.4.5/bin/activate
coverage erase
coverage run `which nosetests` --with-doctest
coverage report --include="${program}/*" --omit="tests/*"
coverage html --include="${program}/*" --omit="tests/*"
flake8 ${program}/__init__.py ${program}/${program}.py ${program}/wdmutil.py --exit-zero
deactivate

