---
name: Build mac wheels

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
    SETUPTOOLS_ENABLE_FEATURES: legacy-editable

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macOS-latest]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4

            - name: Setup Fortran
              uses: awvwgk/setup-fortran@main
              id: setup-fortran
              with:
                  compiler: gcc
                  version: 11
              env:
                  FC: ${{ steps.setup-fortran.outputs.fc }}

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.12.3
              env:
                  CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
                  CIBW_SKIP: pp* cp36-* cp37-*

            - name: Build and upload
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_WDMTOOLBOX_TOKEN }}
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install --upgrade wheel
                  python3 -m pip install --upgrade twine
                  twine upload --verbose --skip-existing wheelhouse/*.whl
