---
name: Build mac wheels

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
    SETUPTOOLS_ENABLE_FEATURES: legacy-editable

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macOS-latest]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4

            - name: Setup Fortran
              uses: fortran-lang/setup-fortran@v1
              id: setup-fortran
              with:
                  compiler: gcc
                  version: 13
            - run: ${{ env.FC }} --version
              env:
                  FC: ${{ steps.setup-fortran.outputs.fc }}
                  CC: ${{ steps.setup-fortran.outputs.cc }}

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.16.5
              env:
                  CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
                  CIBW_SKIP: pp* cp36-* cp37-*

                  CIBW_TEST_REQUIRES: pytest
                  CIBW_TEST_COMMAND: >
                      cd {project} &&
                      pytest

            - name: Upload
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_WDMTOOLBOX_TOKEN }}
              run: |
                  python3 -m pip install --upgrade twine
                  twine upload --verbose --skip-existing wheelhouse/*.whl
