---
name: publish_conda

on:  # yamllint disable-line rule:truthy
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: publish-to-conda
              uses: MichaelsJP/conda-package-publish-action@v1.0.0
              with:
                  subDir: conda_build
                  AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
                  platforms: all
                  override: true
                  dry_run: true
